### ISSUE TITLE
SQLAlchemy: `CompileError: The 'crate' dialect with current database version settings does not support in-place multirow inserts.`

### ISSUE THREAD

**Issue by amotl** [crate/crate-python#534]
Hi,

when [evaluating loading Dask DataFrames into CrateDB](https://gist.github.com/amotl/c8039291fb4b4b16879fd8814de9ecdf) using the `method="multi"` option, the program croaks.

```python
Traceback (most recent call last):
  File "/path/to/lib/python3.10/site-packages/pandas/io/sql.py", line 1325, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/path/to/lib/python3.10/site-packages/pandas/io/sql.py", line 946, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/path/to/lib/python3.10/site-packages/pandas/io/sql.py", line 869, in _execute_insert_multi
    result = conn.execute(stmt)
  File "/path/to/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/path/to/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/path/to/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1630, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/path/to/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 665, in _compile_w_cache
    compiled_sql = self._compiler(
  File "/path/to/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 291, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/path/to/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 1269, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/path/to/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 710, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/path/to/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 755, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/path/to/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 143, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "/path/to/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 5350, in visit_insert
    raise exc.CompileError(
sqlalchemy.exc.CompileError: The 'crate' dialect with current database version settings does not support in-place multirow inserts.
```

With kind regards,
Andreas.

**Comment by amotl** [comment]
I think those are the relevant pointers to the corresponding SQLAlchemy documentation.

- https://docs.sqlalchemy.org/glossary.html#term-executemany
- https://docs.sqlalchemy.org/core/connections.html#engine-insertmanyvalues
- https://docs.sqlalchemy.org/orm/queryguide/dml.html#orm-queryguide-bulk-insert
- https://docs.sqlalchemy.org/orm/queryguide/dml.html#orm-queryguide-legacy-bulk-insert

**Comment by amotl** [comment]
There is now a fix for this issue.

- GH-538

**Comment by seut** [comment]
Looks like it is fixed.
